apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: newspedia
  region: ap-northeast-2
  version: "1.21"

managedNodeGroups:
  - name: workers
    instanceType: t3.medium
    privateNetworking: true
    minSize: 1
    maxSize: 3
    desiredCapacity: 2
    volumeSize: 20
    ssh:
      allow: true
      publicKeyName: newspedia-workspace
    labels: { role: worker }
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        ebs: true
        imageBuilder: true
        efs: true
        albIngress: true
        autoScaler: true
        cloudWatch: true
        externalDNS: true